# Generated by Django 5.0.6 on 2024-08-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="animals/photos/")),
                (
                    "interest",
                    models.TextField(max_length=1000, verbose_name="สิ่งที่น่าสนใจ :"),
                ),
                ("habitat", models.CharField(max_length=100, verbose_name="ถิ่นอาศัย")),
                ("food", models.CharField(max_length=50, verbose_name="อาหาร :")),
                (
                    "behavior",
                    models.TextField(max_length=500, verbose_name="พฤติกรรม :"),
                ),
                ("age", models.CharField(max_length=20, verbose_name="อายุเฉลี่ย")),
                (
                    "reproductive_age",
                    models.CharField(max_length=100, verbose_name="วัยเจริญพันธุ์ :"),
                ),
                (
                    "size_weight",
                    models.CharField(max_length=200, verbose_name="ขนาดและน้ำหนัก :"),
                ),
            ],
        ),
    ]
