# Generated by Django 5.0.6 on 2024-08-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="id",
        ),
        migrations.AddField(
            model_name="animal",
            name="name",
            field=models.CharField(
                default="Unknown",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="ชื่อสัตว์",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="scientific_name",
            field=models.CharField(
                default="ชื่อวิทยาศาสตร์",
                max_length=100,
                verbose_name="ชื่อวิทยาศาสตร์",
            ),
            preserve_default=False,
        ),
    ]
