# Generated by Django 5.0.6 on 2024-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_animal_id_animal_name_animal_scientific_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="category",
            field=models.CharField(
                choices=[
                    ("mammal", "สัตว์เลี้ยงลูกด้วยนม"),
                    ("reptile", "สัตว์เลื้อยคลาน"),
                    ("bird", "สัตว์ปีก"),
                    ("aquatic", "สัตว์น้ำ"),
                    ("amphibian", "สะเทินน้ำสะเทินบก"),
                ],
                default="mammal",
                max_length=20,
                verbose_name="ประเภทสัตว์",
            ),
            preserve_default=False,
        ),
    ]
