# Generated by Django 5.0.6 on 2024-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_animal_age_alter_animal_behavior_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="อายุเฉลี่ย"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="behavior",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="พฤติกรรม"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="food",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="อาหาร"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="habitat",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="ถิ่นอาศัย"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="interest",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="สิ่งที่น่าสนใจ"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="reproductive_age",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="วัยเจริญพันธุ์"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="size_weight",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="ขนาดและน้ำหนัก"
            ),
        ),
    ]
