# Generated by Django 5.0.6 on 2024-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_animal_age_alter_animal_behavior_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mammal", "สัตว์เลี้ยงลูกด้วยนม"),
                    ("reptile", "สัตว์เลื้อยคลาน"),
                    ("bird", "สัตว์ปีก"),
                    ("aquatic", "สัตว์น้ำ"),
                    ("amphibian", "สะเทินน้ำสะเทินบก"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
